package:
  name: hft
  version: 1.0.8s
	
source:
  fn: hft-1.0.8.tar.gz
  url: https://pypi.python.org/packages/93/e4/3a73ae5b84cccdc083a441dfc6669ab575c3d3c3c29ff2c5a863321e1b70/hft-1.0.8.tar.gz
  md5: 433c816b867f5e3e637607a14ce93afd

build:
  number: 1
  noarch_python: False
	
requirements:
  build:
    - python
    - cython
    - wheel	
    - six >=1.7.0
    - jniusx >=1.0.5
    - matplotlib
    - numpy
    - pytz
    - configparser
    
  run:
    - python
    - six >=1.7.0
    - jniusx >=1.0.5
    - matplotlib
    - numpy
    - pytz
    - configparser
    
about:
  home: https://www.portfolioeffect.com
  license: GPLv3
  summary: Python API to PortfolioEffect cloud service for backtesting high frequency trading (HFT) strategies, intraday portfolio analysis and optimization. Includes auto-calibrating model pipeline for market microstructure noise, risk factors, price jumps/outliers, tail risk (high-order moments) and price fractality (long memory). Constructed portfolios could use client-side market data or access HF intraday price history for all major US Equities.